# Generated by Django 5.2.17 on 2026-08-30 06:23

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def create_legacy_enrollments(apps, schema_editor):
    StudentProfile = apps.get_model('portal', 'StudentProfile')
    Enrollment = apps.get_model('portal', 'Enrollment')
    for profile in StudentProfile.objects.exclude(course__isnull=True):
        Enrollment.objects.get_or_create(
            student_id=profile.id,
            course_id=profile.course_id,
            defaults={'joining_date': profile.enrolled_on, 'expiry_date': profile.course_expires_on, 'status': 'active'},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_studentprofile_photo_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='publish_from',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='announcement',
            name='publish_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='published',
            field=models.BooleanField(default=False, help_text='Show this course on the public website.'),
        ),
        migrations.AddField(
            model_name='course',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='status',
            field=models.CharField(choices=[('new', 'New / Pending'), ('contacted', 'Contacted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='new', max_length=12),
        ),
        migrations.AddField(
            model_name='registration',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=25, validators=[django.core.validators.RegexValidator('^[+()\\-\\s0-9]{7,25}$', 'Enter a valid phone number.')], verbose_name='WhatsApp number'),
        ),
        migrations.AddField(
            model_name='studentfeedback',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=25, validators=[django.core.validators.RegexValidator('^[+()\\-\\s0-9]{7,25}$', 'Enter a valid phone number.')]),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='course',
            field=models.ForeignKey(blank=True, help_text='Leave empty for every student.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='portal.course'),
        ),
        migrations.AlterField(
            model_name='classrecording',
            name='video_url',
            field=models.URLField(help_text='Paste the private recording link.'),
        ),
        migrations.AlterField(
            model_name='course',
            name='active',
            field=models.BooleanField(default=True, help_text='Legacy availability setting.'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=120, unique=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='message',
            field=models.TextField(blank=True, max_length=1000, verbose_name='description / question'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='name',
            field=models.CharField(max_length=100, verbose_name='full name'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='phone',
            field=models.CharField(max_length=25, validators=[django.core.validators.RegexValidator('^[+()\\-\\s0-9]{7,25}$', 'Enter a valid phone number.')], verbose_name='mobile number'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='legacy_students', to='portal.course'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='course_expires_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=25, validators=[django.core.validators.RegexValidator('^[+()\\-\\s0-9]{7,25}$', 'Enter a valid phone number.')]),
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joining_date', models.DateField(default=django.utils.timezone.localdate)),
                ('expiry_date', models.DateField(blank=True, help_text='Leave blank for no expiry.', null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=12)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='portal.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='portal.studentprofile')),
            ],
            options={
                'ordering': ['-joining_date', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('student', 'course'), name='unique_student_course_enrollment')],
            },
        ),
        migrations.RunPython(create_legacy_enrollments, migrations.RunPython.noop),
    ]
