# Generated by Django 5.2.17 on 2026-08-30 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_add_starter_course_catalogue'),
    ]

    operations = [
        migrations.DeleteModel(name='ClassRecording'),
        migrations.DeleteModel(name='CourseMaterial'),
        migrations.DeleteModel(name='Enrollment'),
        migrations.RemoveField(model_name='studentfeedback', name='student'),
        migrations.DeleteModel(name='StudentProfile'),
    ]
