# Generated by Django 5.2.17 on 2026-08-30 08:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_remove_student_portal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentfeedback',
            name='video_url',
        ),
        migrations.AddField(
            model_name='studentfeedback',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload an MP4, WebM, or OGG video.', upload_to='student_feedback_videos/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'webm', 'ogg'])], verbose_name='student video'),
        ),
    ]
