# Generated by Django 5.2.17 on 2026-08-30 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_upload_student_feedback_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='whatsapp_group_url',
            field=models.URLField(blank=True, help_text='Optional. Leave blank or clear it when the course group is no longer active.', verbose_name='WhatsApp group link'),
        ),
    ]
