# Generated by Django 5.2.17 on 2026-08-30 17:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_add_announcement_whatsapp_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfeedback',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload an MP4, WebM, or OGG video.', max_length=255, upload_to='student_feedback_videos/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'webm', 'ogg'])], verbose_name='student video'),
        ),
    ]
