services:
  - type: web
    name: work2win-technologies
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: ADMIN_EMAIL
        value: work2wintechnologies@gmail.com
      - key: RESEND_API_KEY
        sync: false
      - key: FROM_EMAIL
        sync: false
